version: "3.3"

services:

  traefik:
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.lehttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.lehttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.lehttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.lehttpchallenge.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.lehttpchallenge.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "letsencrypt-test:/letsencrypt/"

  whoami:
    image: "containous/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roma_whoami.rule=Host(`${TEST_DOMAIN}`)"
      - "traefik.http.routers.roma_whoami.entrypoints=websecure"
      - "traefik.http.routers.roma_whoami.tls.certresolver=lehttpchallenge"

volumes:

  letsencrypt-test:
