version: "3.4"

services:

  api:
    labels:
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      # remote
      - "traefik.http.routers.api.rule=Host(`${API_DOMAIN:-api.wimc.online}`)"
      - "traefik.http.routers.api.tls.certresolver=lehttpchallenge"

  app:
    labels:
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      # remote
      - "traefik.http.routers.app.rule=Host(`${APP_DOMAIN:-app.wimc.online}`)"
      - "traefik.http.routers.app.tls.certresolver=lehttpchallenge"

  auth:
    labels:
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls=true"
      # remote
      - "traefik.http.routers.auth.rule=Host(`${AUTH_DOMAIN:-auth.wimc.online}`)"
      - "traefik.http.routers.auth.tls.certresolver=lehttpchallenge"

  router:
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--log.level=DEBUG"
      # remote
      - "--certificatesresolvers.lehttpchallenge.acme.email=${LE_EMAIL:?}"
      - "--certificatesresolvers.lehttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.lehttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.lehttpchallenge.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.http.routers.router.entrypoints=websecure"
      - "traefik.http.routers.router.tls=true"
      # remote
      - "traefik.http.routers.router.rule=Host(`${ROUTER_DOMAIN:-router.wimc.online}`)"
      - "traefik.http.routers.router.tls.certresolver=lehttpchallenge"
    volumes:
      - "letsencrypt:/letsencrypt/"

  api_db:
    ports:
      - "3306:3306"

volumes:

  letsencrypt:
