version: "3.3"

services:

  api:
    image: "docker.pkg.github.com/wimc-online/api/api:latest"
    volumes:
      - "${API_PATH}:/app"

  api_schema_update:
    image: "docker.pkg.github.com/wimc-online/api/api:latest"

  api_db:
    ports:
      - "3306:3306"

  router:
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # dev
      - "--log.level=DEBUG"
      - "--providers.file.filename=/etc/traefik/certs.yml"
    volumes:
      - "./config/traefik/certs.yml:/etc/traefik/certs.yml"
      - "./certs:/etc/traefik/certs"
