version: "3.3"

services:

  api:
    labels:
      - "traefik.http.routers.api.tls.certresolver=lehttpchallenge"

  auth:
    labels:
      - "traefik.http.routers.auth.tls.certresolver=lehttpchallenge"

  router:
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # pro
      - "--certificatesresolvers.lehttpchallenge.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.lehttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.lehttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.lehttpchallenge.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.http.routers.router.tls.certresolver=lehttpchallenge"
    volumes:
      - "letsencrypt:/letsencrypt/"

volumes:

  letsencrypt:
