version: "3.4"

services:

  api:
    depends_on:
      - "router"
      - "api_db"
    labels:
      - "traefik.enable=true"
    restart: "unless-stopped"
    user: application:application

  api_db:
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - "MYSQL_DATABASE=api"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_USER=user"
    image: "mysql:5.7"
    restart: "unless-stopped"
    volumes:
      - "api_db:/var/lib/mysql"

  auth:
    depends_on:
      - "router"
      - "auth_db"
    environment:
      - "DB_ADDR=auth_db"
      - "DB_DATABASE=auth"
      - "DB_PASSWORD=password"
      - "DB_USER=user"
      - "DB_VENDOR=mysql"
      - "KEYCLOAK_PASSWORD=password"
      - "KEYCLOAK_USER=user"
      - "PROXY_ADDRESS_FORWARDING=true"
    labels:
      - "traefik.enable=true"
    restart: "unless-stopped"

  auth_db:
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - "MYSQL_DATABASE=auth"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_USER=user"
    image: "mysql:5.7"
    restart: "unless-stopped"
    volumes:
      - "auth_db:/var/lib/mysql"

  router:
    image: "traefik:v2.2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=user:$$apr1$$TqPaHVlK$$WMysyGKdwM9RzlGGRNtwU1"
      - "traefik.http.routers.router.middlewares=traefik-auth"
      - "traefik.http.routers.router.service=api@internal"
    ports:
      - "80:80"
      - "443:443"
    restart: "unless-stopped"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:

  api_db:

  auth_db:
