version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_HTPASSWD}"
      - "traefik.http.routers.roma_traefik.entrypoints=websecure"
      - "traefik.http.routers.roma_traefik.middlewares=traefik-auth"
      - "traefik.http.routers.roma_traefik.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.roma_traefik.service=api@internal"
      - "traefik.http.routers.roma_traefik.tls=true"
    ports:
      - "80:80"
      - "443:443"
    restart: "unless-stopped"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  keycloak:
    environment:
      - "KEYCLOAK_USER"
      - "KEYCLOAK_PASSWORD"
      - "PROXY_ADDRESS_FORWARDING=true"
      - "DB_USER=keycloak"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_VENDOR=MYSQL"
      - "DB_ADDR=keycloak_db"
    image: "jboss/keycloak:10.0.1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roma_keycloak.entrypoints=websecure"
      - "traefik.http.routers.roma_keycloak.rule=Host(`${KEYCLOAK_DOMAIN}`)"
      - "traefik.http.routers.roma_keycloak.tls=true"
    restart: "unless-stopped"
    depends_on:
      - "keycloak_db"

  keycloak_db:
    environment:
      - "MYSQL_ROOT_PASSWORD"
      - "MYSQL_DATABASE=keycloak"
      - "MYSQL_USER=keycloak"
      - "MYSQL_PASSWORD"
    image: mysql:5.7
    command: "--default-authentication-plugin=mysql_native_password"
    restart: "unless-stopped"

  api:
    image: "php:7.4-apache"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roma_api.entrypoints=websecure"
      - "traefik.http.routers.roma_api.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.roma_api.tls=true"
    restart: "unless-stopped"
    volumes:
      - "./wimc-api:/var/www"
    working_dir: "/var/www"
    depends_on:
      - "mariadb"

  mariadb:
    environment:
      - "MYSQL_ROOT_PASSWORD"
    image: "mariadb:10.5.3"
    ports:
      - "3306:3306"
    restart: "unless-stopped"
