version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roma_traefik.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.roma_traefik.entrypoints=websecure"
      - "traefik.http.routers.roma_traefik.tls=true"
      - "traefik.http.routers.roma_traefik.service=api@internal"
      - "traefik.http.routers.roma_traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_HTPASSWD}"
    ports:
      - "80:80"
      - "443:443"
    restart: "unless-stopped"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  keycloak:
    image: "quay.io/keycloak/keycloak:10.0.1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roma_keycloak.rule=Host(`${KEYCLOAK_DOMAIN}`)"
      - "traefik.http.routers.roma_keycloak.entrypoints=websecure"
      - "traefik.http.routers.roma_keycloak.tls=true"
    restart: "unless-stopped"

  api:
    image: "amazon/amazon-ecs-sample"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roma_api.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.roma_api.entrypoints=websecure"
      - "traefik.http.routers.roma_api.tls=true"
    restart: "unless-stopped"
