version: "3.4"

services:

  api:
    environment:
      - "APP_ENV=dev"
      - "APP_DEBUG=1"
    image: "docker.pkg.github.com/wimc-online/api/api:latest"
    volumes:
      - "${API_PATH:?}:/app"

  api_db:
    ports:
      - "3306:3306"

  auth:
    image: "docker.pkg.github.com/wimc-online/auth/auth:latest"
