version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  keycloak:
    image: "quay.io/keycloak/keycloak:10.0.1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roma_keycloak.rule=Host(`${KEYCLOAK_DOMAIN}`)"
    restart: "unless-stopped"

  api:
    image: "amazon/amazon-ecs-sample"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roma_api.rule=Host(`${API_DOMAIN}`)"
    restart: "unless-stopped"
