version: "3.4"

services:

  api:
    image: "docker.pkg.github.com/wimc-online/api/api:0.0.15"

  app:
    image: "docker.pkg.github.com/wimc-online/app/app:0.0.15"

  auth:
    image: "docker.pkg.github.com/wimc-online/auth/auth:0.0.4"
