version: "3.3"

services:

  api:
    depends_on:
      - "router"
      - "api_db"
      - "api_schema_update"
    image: "docker.pkg.github.com/wimc-online/api/api:0.0.1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.api.tls=true"
    restart: "unless-stopped"

  api_db:
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - "MYSQL_DATABASE=api"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_USER=user"
    image: "mysql:5.7"
    restart: "unless-stopped"
    volumes:
      - "api_db:/var/lib/mysql"

  api_schema_update:
    command: "bin/console doctrine:schema:update --force"
    depends_on:
      - "api_db"
    image: "docker.pkg.github.com/wimc-online/api/api:0.0.1"
    restart: "no"

  auth:
    depends_on:
      - "router"
      - "auth_db"
    environment:
      - "DB_ADDR=auth_db"
      - "DB_DATABASE=auth"
      - "DB_PASSWORD=password"
      - "DB_USER=user"
      - "DB_VENDOR=mysql"
      - "KEYCLOAK_PASSWORD=password"
      - "KEYCLOAK_USER=user"
      - "PROXY_ADDRESS_FORWARDING=true"
    image: "jboss/keycloak:10.0.1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.rule=Host(`${AUTH_DOMAIN}`)"
      - "traefik.http.routers.auth.tls=true"
    restart: "unless-stopped"

  auth_db:
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - "MYSQL_DATABASE=auth"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_USER=user"
    image: "mysql:5.7"
    restart: "unless-stopped"
    volumes:
      - "auth_db:/var/lib/mysql"

  router:
    image: "traefik:v2.2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=user:$$apr1$$TqPaHVlK$$WMysyGKdwM9RzlGGRNtwU1"
      - "traefik.http.routers.router.entrypoints=websecure"
      - "traefik.http.routers.router.middlewares=traefik-auth"
      - "traefik.http.routers.router.rule=Host(`${ROUTER_DOMAIN}`)"
      - "traefik.http.routers.router.service=api@internal"
      - "traefik.http.routers.router.tls=true"
    ports:
      - "80:80"
      - "443:443"
    restart: "unless-stopped"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:

  api_db:

  auth_db:
