version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_HTPASSWD}"
      - "traefik.http.routers.roma_traefik.entrypoints=websecure"
      - "traefik.http.routers.roma_traefik.middlewares=traefik-auth"
      - "traefik.http.routers.roma_traefik.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.roma_traefik.service=api@internal"
      - "traefik.http.routers.roma_traefik.tls=true"
    ports:
      - "80:80"
      - "443:443"
    restart: "unless-stopped"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  keycloak:
    environment:
      - "KEYCLOAK_USER"
      - "KEYCLOAK_PASSWORD"
      - "PROXY_ADDRESS_FORWARDING=true"
    image: "jboss/keycloak:10.0.1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roma_keycloak.entrypoints=websecure"
      - "traefik.http.routers.roma_keycloak.rule=Host(`${KEYCLOAK_DOMAIN}`)"
      - "traefik.http.routers.roma_keycloak.tls=true"
    restart: "unless-stopped"

  api:
    image: "amazon/amazon-ecs-sample"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roma_api.entrypoints=websecure"
      - "traefik.http.routers.roma_api.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.roma_api.tls=true"
    restart: "unless-stopped"

  mariadb:
    environment:
      - "MYSQL_ROOT_PASSWORD"
    image: "mariadb:10.5.3"
    ports:
      - "3306:3306"
    restart: "unless-stopped"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roma_phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.roma_phpmyadmin.rule=Host(`${PHPMYADMIN_DOMAIN}`)"
      - "traefik.http.routers.roma_phpmyadmin.tls=true"
    environment:
      - PMA_ARBITRARY=1
    restart: "unless-stopped"
