name: Deploy to host
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.DOCKER_HOST }} >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.DOCKER_PRIVATE_KEY }}"
    - name: Pull docker images and update services
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        DOCKER_HOST: ssh://${{ secrets.DOCKER_USER }}@${{ secrets.DOCKER_HOST }}
        LE_EMAIL: ${{ secrets.LE_EMAIL }}
        API_JWT_PUBLIC_KEY: ${{ secrets.API_JWT_PUBLIC_KEY }}
      run: |
        echo "${{ secrets.GPR_PASSWORD }}" | docker login https://docker.pkg.github.com -u "${{ secrets.GPR_USER }}" --password-stdin
        printf 'API_JWT_PUBLIC_KEY=%s' $API_JWT_PUBLIC_KEY > .env
        docker-compose -f docker-compose.yml -f docker-compose.remote.yml -f docker-compose.prod.yml pull
        docker-compose -f docker-compose.yml -f docker-compose.remote.yml -f docker-compose.prod.yml up --detach
